package tg.fitnessbot.services.AI.impl;

import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import tg.fitnessbot.api.OpenAIClient;
import tg.fitnessbot.services.AI.LLMService;
@Service
public class LLMServiceImpl implements LLMService {
    @Autowired
    OpenAIClient openAIClient;

    @Override
    public String processAudio(String audio) {
        ResponseEntity<String> response = openAIClient.getResponse(audio);
        JSONObject mainJson = new JSONObject(response.getBody());
        JSONArray jsons = mainJson.getJSONArray("output");
        // TODO Плохая практика, так делать нельзя!
        // return jsons.getJSONObject(0).getJSONArray("content").getJSONObject(0).getString("text");
        // Выдержка из доков гптшки:
        /*
        The output array often has more than one
        item in it! It can contain tool calls,
        data about reasoning tokens generated by
        reasoning models, and other items. It is
        not safe to assume that the model's text
        output is present at output[0].content[0].text.
         */
        for (int i = 0; i < jsons.length(); i++) {
            JSONObject json = jsons.getJSONObject(i);
            if (json.has("content")) {
                JSONArray content = json.getJSONArray("content");
                for (int j = 0; j < content.length(); j++) {
                    JSONObject contentJson = content.getJSONObject(j);
                    if (contentJson.has("text")) {
                        return contentJson.getString("text");
                    }
                }
            }
        }
        return "не удалось получить данные от OpenAI";



    }
}
