package tg.fitnessbot.services.AI.impl;

import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import tg.fitnessbot.api.OpenAIClient;
import tg.fitnessbot.services.AI.LLMService;
@Service
public class LLMServiceImpl implements LLMService {
    @Autowired
    OpenAIClient openAIClient;

    @Override
    public String processAudio(String audio) {
        ResponseEntity<String> response = openAIClient.getResponse(audio);
        JSONObject json = new JSONObject(response.getBody());
        JSONArray jsons = json.getJSONArray("output");
        // TODO Плохая практика, так делать нельзя!
        // Выдержка из доков гптшки:
        /*
        The output array often has more than one
        item in it! It can contain tool calls,
        data about reasoning tokens generated by
        reasoning models, and other items. It is
        not safe to assume that the model's text
        output is present at output[0].content[0].text.
         */
        return jsons.getJSONObject(0).getJSONArray("content").getJSONObject(0).getString("text");
    }
}
